trainer:
  init:
    model_dir: ./model_dir/sdk_benchmark/cholesky
    seed: 1
    backend: {}
    model:
      name: sdk_benchmark/cholesky
      matrix_size: 40
    loop:
      eval_steps: 4
    checkpoint:
      steps: null
    logging:
      log_steps: 1
  validate:
    val_dataloader:
      data_processor: SdkBenchmarkCholeskyDataProcessor
      batch_size: 1
      sample_count: 4
      matrix_size: 40
