trainer:
  init:
    model_dir: ./model_dir/sdk-benchmark/spmv-hypersparse
    seed: 1
    backend: {}
    model:
      name: sdk_benchmark/spmv-hypersparse
      rows: 16
      cols: 16
    loop:
      eval_steps: 10
    checkpoint:
      steps: null
  validate:
    val_dataloader:
      data_processor: SdkBenchmarkSpmvHypersparseDataProcessor
      batch_size: 1
      sample_count: 10
      rows: 16
      cols: 16
