trainer:
  init:
    seed: 42
    model:
      name: gnn
      task:
        compute_eval_metrics: false
        disable_log_softmax: false
        to_float16: true
      architecture:
        type: graphsage
        hidden_dim: 1024
        num_layers: 3
        dropout: 0.5
        aggregator: mean
        n_feat: 128
        n_class: 40
    optimizer:
      AdamW:
        params: []
        weight_decay: 0.0005
        learning_rate: 0.003
        eps: 1.0e-06
        betas:
        - 0.9
        - 0.999
    precision:
      enabled: true
      fp16_type: float16
      loss_scaling_factor: dynamic
    model_dir: $MODELZOO_ROOT/../../../model_dirs/ogbn_arxiv_graphsage_accuracy_nocache
    loop:
      max_steps: 500
      steps_per_epoch: 20
      eval_frequency: 20
    logging:
      log_steps: 20
    checkpoint: {}
    backend:
      backend_type: CSX
      cluster_config:
        num_csx: 1
        num_workers_per_csx: 1
  fit:
    train_dataloader:
      data_processor: GNNDataProcessor
      sampling_mode: neighbor
      fanouts: &id001
      - 15
      - 10
      - 5
      batch_size: 4096
      drop_last_batch: false
      num_workers: 40
      prefetch_factor: 2
      persistent_workers: true
      pin_memory: true
      sampler_seed: 42
      shuffle: true
      cache_fraction: null
      split: train
      dataset_profiles: &id002
        ogbn_arxiv:
          dataset_name: ogbn-arxiv
          data_dir: $MODELZOO_ROOT/models/gnn/data/datasets
          pad_node_id: 0
      dataset: ogbn_arxiv
      static_batch_cache_size: 0
      use_fake_data: false
      worker_diagnostics:
        enabled: false
    val_dataloader:
      data_processor: GNNDataProcessor
      sampling_mode: neighbor
      fanouts: *id001
      batch_size: 4096
      drop_last_batch: false
      num_workers: 40
      prefetch_factor: 2
      persistent_workers: true
      pin_memory: true
      sampler_seed: 42
      shuffle: false
      split: valid
      dataset_profiles: *id002
      dataset: ogbn_arxiv
      cache_fraction: null
      static_batch_cache_size: 0
      use_fake_data: false
      worker_diagnostics:
        enabled: false
  validate:
    val_dataloader:
      data_processor: GNNDataProcessor
      sampling_mode: neighbor
      fanouts: *id001
      batch_size: 4096
      drop_last_batch: false
      num_workers: 40
      prefetch_factor: 2
      persistent_workers: true
      pin_memory: true
      sampler_seed: 42
      shuffle: false
      split: valid
      dataset_profiles: *id002
      dataset: ogbn_arxiv
  validate_all:
    val_dataloaders:
    - data_processor: GNNDataProcessor
      sampling_mode: neighbor
      fanouts: *id001
      batch_size: 4096
      drop_last_batch: false
      num_workers: 40
      prefetch_factor: 2
      persistent_workers: true
      pin_memory: true
      sampler_seed: 42
      shuffle: false
      split: valid
      dataset_profiles: *id002
      dataset: ogbn_arxiv
runconfig:
  python_paths:
  - $MODELZOO_ROOT/../..
