"""Render paper tables from audited HPC Asia TSVs; no raw-data mutation.

Run the raw-log analysis scripts before this renderer. --check verifies that
committed/generated TeX and its input hashes match the current TSVs.
"""
from __future__ import annotations

import argparse
import csv
import hashlib
import json
from pathlib import Path
from statistics import mean, stdev

ROOT = Path(__file__).resolve().parents[3]
SOURCE = ROOT / "results"
DEST = ROOT / "tables"


def rows(name):
    with (SOURCE / name).open(newline="") as stream:
        return list(csv.DictReader(stream, delimiter="\t"))


def pm(avg, sd, digits=1):
    return f"${avg:,.{digits}f} \\pm {sd:,.{digits}f}$"


def table(env, caption, label, spec, headings, body):
    return "\n".join([
        "% Generated by analyze/scripts/paper/build_hpcasia_tables.py.",
        f"\\begin{{{env}}}[t]", r"  \centering", r"  \small",
        r"  \setlength{\tabcolsep}{4pt}",
        f"  \\caption{{{caption}}}", f"  \\label{{{label}}}",
        f"  \\begin{{tabular}}{{{spec}}}", r"    \hline",
        "    " + " & ".join(headings) + r" \\", r"    \hline",
        *["    " + " & ".join(row) + r" \\" for row in body],
        r"    \hline", r"  \end{tabular}", f"\\end{{{env}}}", "",
    ])


def render():
    learning = rows("learning/summary.tsv")
    assert {(r['dataset'], r['platform']) for r in learning} == {
        (d, p) for d in ('arxiv', 'products') for p in ('cs3', 'h100')}
    assert all(int(r['n']) == 3 and int(r['evaluation_count']) == 25 for r in learning)
    body = [[r['dataset'], 'CS-3' if r['platform'] == 'cs3' else 'H100/PyG',
             pm(100*float(r['final_accuracy_mean']), 100*float(r['final_accuracy_sample_sd']), 2),
             pm(100*float(r['best_accuracy_mean']), 100*float(r['best_accuracy_sample_sd']), 2)]
            for r in learning]
    output = {'accuracy.tex': table('table',
        'Validation accuracy (\\%), mean $\\pm$ sample SD over three seeds. Final values use step 500 (arxiv) or 1000 (products); best values are selected from the 25 validation evaluations within each run.',
        'tab:accuracy', '@{}llrr@{}', ['Dataset', 'Path', 'Final', 'Best'], body)}
    perf = {(r['dataset'],r['cache'],r['platform']):r for r in rows('throughput/summary.tsv')}
    assert len(perf) == 8
    body=[]
    for d in ('arxiv','products'):
        for c in ('0','1'):
            a,b=[perf[d,c,p] for p in ('cs3','h100')]
            assert a['n']==b['n']==('9' if c=='0' else '3')
            assert a['start_step']==b['start_step']=='40'
            assert a['end_step']==b['end_step']==('840' if d=='arxiv' else '1640')
            body.append([d, r'\cachenone' if c=='0' else r'\cachefull',
                         pm(float(a['mean']),float(a['sample_stddev'])),
                         pm(float(b['mean']),float(b['sample_stddev'])),
                         f"{100*float(a['mean'])/float(b['mean']):.2f}", a['n']])
    output['throughput.tex']=table('table*',
        'Training-loop throughput in actual target vertices/s, mean $\\pm$ sample SD across independent jobs. Uncached conditions use three seeds with three runs per seed; cached conditions use three seeds with one run per seed. Ratios divide the two means. CS-3 caches features in Worker-host CPU memory and H100/PyG in GPU memory.',
        'tab:throughput','@{}llrrrr@{}',
        ['Dataset','Cache','CS-3/Model Zoo','H100/PyG','CS-3/H100 (\\%)','$n$/path'],body)
    workers=rows('worker_repeat_review/runs.tsv')
    body=[]
    for w in (4,8,12,16):
        group=[r for r in workers if int(r['workers'])==w]
        assert len(group)==6
        assert all(r['start_step']=='40' and r['end_step']=='440' and r['seed']=='42' for r in group)
        vals=[float(r['targets_per_second']) for r in group]
        body.append([str(w),str(len(vals)),pm(mean(vals),stdev(vals))])
    assert len(workers)==24
    assert len({r['input_order_sha256'] for r in workers})==1
    output['workers.tex']=table('table',
        'CS-3 worker-count sensitivity on arxiv, seed 42, steps 40--440; mean $\\pm$ sample SD over six jobs per worker count. All 24 completed jobs match the model, input contract, and loader settings except worker count.',
        'tab:workers','@{}rrr@{}',['Loader workers','$n$','Actual targets/s'],body)
    controls=rows('input_pipeline/cs3_input_interventions.tsv')
    names={'baseline':'Baseline','prefetch1':'Prefetch = 1','persistent_off':'Worker persistence off','feature_cache':'Host feature cache','static_batch':'Prepared-batch replay'}
    base=mean(float(r['throughput']) for r in controls if r['control']=='baseline')
    body=[]
    for key,label in names.items():
        group=[r for r in controls if r['control']==key]
        assert len(group)==3 and all(r['metric']=='nominal_slots_per_second' for r in group)
        vals=[float(r['throughput']) for r in group]
        body.append([label,pm(mean(vals),stdev(vals)),f'{mean(vals)/base:.3f}'])
    output['interventions.tex']=table('table',
        'CS-3 input interventions on arxiv with four workers, seed 42, steps 40--440; three jobs per condition. These earlier controls count nominal slots/s, including padding, and form a separate series from Table~\\ref{tab:workers}. Values are mean $\\pm$ sample SD.',
        'tab:interventions','@{}lrr@{}',['Condition','Slots/s','Ratio'],body)
    inputs=['learning/summary.tsv','throughput/summary.tsv','worker_repeat_review/runs.tsv','input_pipeline/cs3_input_interventions.tsv']
    output['provenance.json']=json.dumps({
        'generator':str(Path(__file__).resolve().relative_to(ROOT)),
        'generator_sha256':hashlib.sha256(Path(__file__).read_bytes()).hexdigest(),
        'inputs':{str((SOURCE/f).relative_to(ROOT)):hashlib.sha256((SOURCE/f).read_bytes()).hexdigest() for f in inputs},
        'outputs':{k:hashlib.sha256(v.encode()).hexdigest() for k,v in output.items()},
    },indent=2)+'\n'
    return output


def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check',action='store_true')
    args=parser.parse_args()
    outputs=render()
    if args.check:
        bad=[name for name,data in outputs.items() if not (DEST/name).exists() or (DEST/name).read_text()!=data]
        if bad:
            raise SystemExit('Stale generated paper tables: '+', '.join(bad))
        print('All 4 paper tables and provenance match audited TSVs.')
    else:
        DEST.mkdir(parents=True,exist_ok=True)
        for name,data in outputs.items():
            (DEST/name).write_text(data)
        print('Rendered 4 paper tables and provenance.')


if __name__=='__main__':
    main()
